{
 "title": "Kafka metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Assigned partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_assigned_partitions"
    }
   ]
  },
  {
   "title": "Kafka consumed bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_bytes_consumed_total_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Consumed records/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_records_consumed_total_records_total[1m])"
    }
   ]
  },
  {
   "title": "Consumers lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_records"
    }
   ]
  }
 ]
}